version: '3.8'
services:
  t_med_user:
    container_name: t_med_user
    image: t_med_user:latest
    deploy:
      restart_policy:
        condition: on-failure
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "7002:80"
