export * from './headerBanner'
export * from './institution'
export * from './statistics'
export * from './managers'
export * from './centralHospital'
export * from './doctorList'
export * from './serviceList'
export * from './news'