export enum AppPathEnum {
  HOME = "/",
  ABOUT = "/about",
  ADMINISTRATION = "/administration",
  MANAGEMENT = "/management",
  STRUCTURE = "/structure",
  DOCS = "/docs",
  MINISTERIAL_DECISION = "/ministerial-decision",
  PRESIDENTIAL_DECREE = "/presidential-decree",
  NEWS = "/news",
  INFO = "/info",
  PROFILE = "/profile",
  STREAM = "/stream",
  INSTITUTION = "/institution",
  CLINIC_SERVICE = "/clinic-service",
  ADMIN = "/admin",
  DASHBOARD = "/dashboard",
  ABOUTUS = "/about-us",
  DOC = "/doc",
  NEW = "/new",
  KNOWLEDGE = "/knowledge",
  POST = "/post",
}
