import { MainLayout } from '@/widgets/layout'
import React, { Suspense } from 'react'
import { Loader, RootLayoutProps } from '@/shared'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { ToastContainer } from 'react-toastify';
import ScrollToTop from "@/shared/utils/scrollToTop";

export const metadata = {
  title: 'T-MED',
  // description: 'Generated by create next app',
}
export default async function RootLayout({ children, params: { locale } }: RootLayoutProps) {
  const messages = await getMessages()
  return (
    <html lang={locale}>
    <body>
    <NextIntlClientProvider messages={messages}>
      <Suspense fallback={<Loader />}>
        <MainLayout>
          {children}
          <ToastContainer />
          {/*<ScrollToTop />*/}
        </MainLayout>
      </Suspense>
    </NextIntlClientProvider>
    </body>
    </html>
  )
}
