name: CI_CD

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/dwed_main
          chmod 600 ~/.ssh/dwed_main
          ssh-keyscan -H 192.168.88.3 >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
          echo "Deployment STARTED"
          ssh -i ~/.ssh/dwed_main root@192.168.88.3 << 'EOF'
            /bin/bash /opt/api.t-med.uz-backend/BMS/deploy.sh
          EOF
          echo "Deployment FINISHED"
